# This file was generated by GoReleaser. DO NOT EDIT.
cask "apkingo" do
  name "apkingo"
  desc "Tool to extract info from APK files"
  homepage "https://github.com/andpalmier/apkingo"
  version "2.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apkingo"

  on_macos do
    on_intel do
      url "https://github.com/andpalmier/apkingo/releases/download/v#{version}/apkingo_Darwin_x86_64.tar.gz"
      sha256 "0c232f1e2494fe2e8718b3eabd8788dbc7cdc668a6c5f97187e2fe70f7336b46"
    end
    on_arm do
      url "https://github.com/andpalmier/apkingo/releases/download/v#{version}/apkingo_Darwin_arm64.tar.gz"
      sha256 "e81258f1fad17a68f53706bbaf64e94750045abd83a6738ddb9977df84f5639f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andpalmier/apkingo/releases/download/v#{version}/apkingo_Linux_x86_64.tar.gz"
      sha256 "4dd804c259bc2e14d4c54896ada4f1e6a1690fd246e7504f9c3fe3b0381835d5"
    end
    on_arm do
      url "https://github.com/andpalmier/apkingo/releases/download/v#{version}/apkingo_Linux_arm64.tar.gz"
      sha256 "6f07daf9949c6f18805352c58376b943844855121e426e3719c4683139696861"
    end
  end

  # No zap stanza required
end
