# This file was generated by GoReleaser. DO NOT EDIT.
cask "apkingo" do
  version "2.4.3"

  on_macos do
    on_arm do
      sha256 "e4937ae6411387e7912e62d6efacfd8882b9a394bba3f72f373fc0a7e25113c7"
      url "https://github.com/andpalmier/apkingo/releases/download/v#{version}/apkingo_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3118f56ccf534e49e65c13e3b40a5a51023f91b4254a22e77707805369fb4eef"
      url "https://github.com/andpalmier/apkingo/releases/download/v#{version}/apkingo_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "432d2d11d6e674fb8f2e3c16342a415a5ea149cf58194696a482c7df43774569"
      url "https://github.com/andpalmier/apkingo/releases/download/v#{version}/apkingo_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "424ed15ce53d10f58b8b32c15a3834de41830c65098cf2b39fd229d811e7f4e5"
      url "https://github.com/andpalmier/apkingo/releases/download/v#{version}/apkingo_Linux_x86_64.tar.gz"
    end
  end

  name "apkingo"
  desc "Tool to extract info from APK files"
  homepage "https://github.com/andpalmier/apkingo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apkingo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/apkingo"]
    end
  end

  # No zap stanza required
end
