# This file was generated by GoReleaser. DO NOT EDIT.
cask "apkingo" do
  version "2.5.0"

  on_macos do
    on_arm do
      sha256 "32926d81d306d094fdd4a2c696a5447f565bb8532622243952dd88ff4b8be851"
      url "https://github.com/andpalmier/apkingo/releases/download/v#{version}/apkingo_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9f730e665fa62dbfc7f1c64e095986523c1c1e8faff6ac36992e2560ebdf292a"
      url "https://github.com/andpalmier/apkingo/releases/download/v#{version}/apkingo_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ef211ebd95a8893a0377688589ceff817b229b286a170e0aafc784b414d69488"
      url "https://github.com/andpalmier/apkingo/releases/download/v#{version}/apkingo_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "43732672296cf362ed5af5772f598c3f768caf5a8b64fec26cb45737f2ce5abb"
      url "https://github.com/andpalmier/apkingo/releases/download/v#{version}/apkingo_Linux_x86_64.tar.gz"
    end
  end

  name "apkingo"
  desc "Tool to extract info from APK files"
  homepage "https://github.com/andpalmier/apkingo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apkingo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/apkingo"]
    end
  end

  # No zap stanza required
end
