# This file was generated by GoReleaser. DO NOT EDIT.
cask "mbzr" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "843ecac3c2dfa6d8b6f6ff7e8d5c70ca04561e2439927a01f87015169a0f9a1a"
      url "https://github.com/andpalmier/mbzr/releases/download/v#{version}/mbzr_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/andpalmier/mbzr"
    end
    on_intel do
      sha256 "c6f33caa1c55a3f344f79f78120377984e8dc1cf3fa8687fef908e1c819fdb77"
      url "https://github.com/andpalmier/mbzr/releases/download/v#{version}/mbzr_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/andpalmier/mbzr"
    end
  end
  on_linux do
    on_arm do
      sha256 "e483849bbf30eb0b5d6764a8af3f76e431c2c1e59c7a8f87085628a7a9a3ed7c"
      url "https://github.com/andpalmier/mbzr/releases/download/v#{version}/mbzr_#{version}_linux_arm64.tar.gz",
        verified: "github.com/andpalmier/mbzr"
    end
    on_intel do
      sha256 "c06555a6cda8650e9f989db449ef56c2e5e6049bb32f42fe13eefc29a08e6c68"
      url "https://github.com/andpalmier/mbzr/releases/download/v#{version}/mbzr_#{version}_linux_amd64.tar.gz",
        verified: "github.com/andpalmier/mbzr"
    end
  end

  name "mbzr"
  desc "CLI tool to search in MalwareBazaar database and submit samples"
  homepage "https://github.com/andpalmier/mbzr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mbzr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mbzr"]
    end
  end

  # No zap stanza required
end
