# This file was generated by GoReleaser. DO NOT EDIT.
cask "mbzr" do
  name "mbzr"
  desc "CLI tool to search in MalwareBazaar database and submit samples"
  homepage "https://github.com/andpalmier/mbzr"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mbzr"

  on_macos do
    on_intel do
      url "https://github.com/andpalmier/mbzr/releases/download/v#{version}/mbzr_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/andpalmier/mbzr"
      sha256 "f8c4acb23cf43e44032fe99fd9bee98afe418fad1b6a996f0c0271464bb96f51"
    end
    on_arm do
      url "https://github.com/andpalmier/mbzr/releases/download/v#{version}/mbzr_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/andpalmier/mbzr"
      sha256 "845cb062861e8c89634b2f2438c8d4f79b81ea33d5be4f7dbd48fa9e9bd40b21"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andpalmier/mbzr/releases/download/v#{version}/mbzr_#{version}_linux_amd64.tar.gz",
        verified: "github.com/andpalmier/mbzr"
      sha256 "284950800950bf643b6e417721a8c429b67971f9f067f302a3e2836dd12da2cf"
    end
    on_arm do
      url "https://github.com/andpalmier/mbzr/releases/download/v#{version}/mbzr_#{version}_linux_arm64.tar.gz",
        verified: "github.com/andpalmier/mbzr"
      sha256 "4d703fdb043143fd7130d8cd469445c8f8c955501404df88f015fb65e231215f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mbzr"]
    end
  end

  # No zap stanza required
end
