# This file was generated by GoReleaser. DO NOT EDIT.
cask "mbzr" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "adec7809df051d1b48438b54ce22f6ca473506bd74c91b45b85c89c5710b762c"
      url "https://github.com/andpalmier/mbzr/releases/download/v#{version}/mbzr_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/andpalmier/mbzr"
    end
    on_intel do
      sha256 "adb2a85b18e359c6684546b3cc8bf6e588bef13d4b3abb4ca3fbce88dab54163"
      url "https://github.com/andpalmier/mbzr/releases/download/v#{version}/mbzr_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/andpalmier/mbzr"
    end
  end
  on_linux do
    on_arm do
      sha256 "f64a8dd3232e7fa566245affe88d8c5ffc34d27aeeb268e5201351aec59dde7f"
      url "https://github.com/andpalmier/mbzr/releases/download/v#{version}/mbzr_#{version}_linux_arm64.tar.gz",
        verified: "github.com/andpalmier/mbzr"
    end
    on_intel do
      sha256 "0fedf8f87acd6a0edbe9e02d788c3162f2ffc384417c77858e13a935e4627f53"
      url "https://github.com/andpalmier/mbzr/releases/download/v#{version}/mbzr_#{version}_linux_amd64.tar.gz",
        verified: "github.com/andpalmier/mbzr"
    end
  end

  name "mbzr"
  desc "CLI tool to search in MalwareBazaar database and submit samples"
  homepage "https://github.com/andpalmier/mbzr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mbzr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mbzr"]
    end
  end

  # No zap stanza required
end
