# This file was generated by GoReleaser. DO NOT EDIT.
cask "repopsy" do
  version "2.1.0"

  on_macos do
    on_arm do
      sha256 "a4b5e81c36a490207ca811501eacbc09feff30651eeaaa65256326d4a2da34c0"
      url "https://github.com/andpalmier/repopsy/releases/download/v#{version}/repopsy_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "09d69d90a2d238101cdb7cfbfb234bc409ef87adf7e07e038f46fbd4c6b4947a"
      url "https://github.com/andpalmier/repopsy/releases/download/v#{version}/repopsy_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "64fd09bff6caac039d1da6a012c7db97ed42f1c85259da95d113cf9d53c057e7"
      url "https://github.com/andpalmier/repopsy/releases/download/v#{version}/repopsy_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0c733c019aefc5d779ecc1ad80653572b4444200883955763c0914b0585d8fb7"
      url "https://github.com/andpalmier/repopsy/releases/download/v#{version}/repopsy_#{version}_linux_amd64.tar.gz"
    end
  end

  name "repopsy"
  desc "Forensic tool for analyzing git repository history"
  homepage "https://github.com/andpalmier/repopsy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repopsy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/repopsy"]
    end
  end

  # No zap stanza required
end
