# This file was generated by GoReleaser. DO NOT EDIT.
cask "repopsy" do
  version "2.0.1"

  on_macos do
    on_arm do
      sha256 "20b5410e6942c84a005e0a936f4741e217ec91ef165e4749046d0e57a15ce011"
      url "https://github.com/andpalmier/repopsy/releases/download/v#{version}/repopsy_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c64fc82c29705d82e0352777b85e1e9bafc46382d76398353f41cd6055411667"
      url "https://github.com/andpalmier/repopsy/releases/download/v#{version}/repopsy_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "78234efb034a23875fead34c6c38e028e1d58d24353c40effc66c5221f05fd21"
      url "https://github.com/andpalmier/repopsy/releases/download/v#{version}/repopsy_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c9e651ee3a22068ff0f8da9e81abed7c594f1815e70ffa13c9d1f5e4f5ff4656"
      url "https://github.com/andpalmier/repopsy/releases/download/v#{version}/repopsy_#{version}_linux_amd64.tar.gz"
    end
  end

  name "repopsy"
  desc "Forensic tool for analyzing git repository history"
  homepage "https://github.com/andpalmier/repopsy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repopsy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/repopsy"]
    end
  end

  # No zap stanza required
end
