# This file was generated by GoReleaser. DO NOT EDIT.
cask "repopsy" do
  version "2.0.0"

  on_macos do
    on_arm do
      sha256 "38622911040d1098b37eb3e808213e8b16ec07187afa1e68071f100e2b8daa4c"
      url "https://github.com/andpalmier/repopsy/releases/download/v#{version}/repopsy_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6b864b5945912914715a6a79cfd4b7e5dd9cc6724ccf5b23eea1f5a82ee57492"
      url "https://github.com/andpalmier/repopsy/releases/download/v#{version}/repopsy_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9a05170f3d8a4b3e8396c9fa35e4de3364b761b930d6a2025bc4599fd8adb066"
      url "https://github.com/andpalmier/repopsy/releases/download/v#{version}/repopsy_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "76259fe6be43af5b6091dd04719ad18fcd5c8454df1cecc7a64fa3bf40be8728"
      url "https://github.com/andpalmier/repopsy/releases/download/v#{version}/repopsy_#{version}_linux_amd64.tar.gz"
    end
  end

  name "repopsy"
  desc "Forensic tool for analyzing git repository history"
  homepage "https://github.com/andpalmier/repopsy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repopsy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/repopsy"]
    end
  end

  # No zap stanza required
end
