# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfox" do
  name "tfox"
  desc "CLI tool to search in ThreatFox IOC database"
  homepage "https://github.com/andpalmier/tfox"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfox"

  on_macos do
    on_intel do
      url "https://github.com/andpalmier/tfox/releases/download/v#{version}/tfox_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/andpalmier/tfox"
      sha256 "ec4b7574ffc937e8a31c5f7104366dd6680731fef1c40e839b985cf7b13fdacd"
    end
    on_arm do
      url "https://github.com/andpalmier/tfox/releases/download/v#{version}/tfox_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/andpalmier/tfox"
      sha256 "7ec5e71223684179b03f9ce1a130044567836acc66940392eece8dcd3d0f9a9c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andpalmier/tfox/releases/download/v#{version}/tfox_#{version}_linux_amd64.tar.gz",
        verified: "github.com/andpalmier/tfox"
      sha256 "ffe9ad7f6a14d8cb334521247c29e17c5e4996b6ba9c252da53cdf3e72211e66"
    end
    on_arm do
      url "https://github.com/andpalmier/tfox/releases/download/v#{version}/tfox_#{version}_linux_arm64.tar.gz",
        verified: "github.com/andpalmier/tfox"
      sha256 "de814ee24f07211e65c0ccbcc9017872f557436b752704cc01cda14e2ee84cb1"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfox"]
    end
  end

  # No zap stanza required
end
