# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfox" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "01be486c26f2ee4ee14c3bb856477da545a7aeec1303ac4e45fe09c41812e62b"
      url "https://github.com/andpalmier/tfox/releases/download/v#{version}/tfox_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4635cf55430265ca4e53008a4ea64a5578a4f37088a0ff158e95746784fb7e19"
      url "https://github.com/andpalmier/tfox/releases/download/v#{version}/tfox_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "57f3110a9495adfabce4e81426496f05542ff6fc7160d1ba28ba2036358ddd4b"
      url "https://github.com/andpalmier/tfox/releases/download/v#{version}/tfox_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "82de3c466bf5519b5f7f2141c6f66fa170a0ce380c60cd9fba31bf2d3af3edd5"
      url "https://github.com/andpalmier/tfox/releases/download/v#{version}/tfox_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tfox"
  desc "CLI tool to search in ThreatFox IOC database"
  homepage "https://github.com/andpalmier/tfox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfox"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfox"]
    end
  end

  # No zap stanza required
end
