# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfox" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "a297944026e545dee5064ea86ba001e3f465de8a1e801864f6d332e38a8a394f"
      url "https://github.com/andpalmier/tfox/releases/download/v#{version}/tfox_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8b7c0070266081b7f8807a6dfd94cfe0c3b62dda66a72881d67ccfa02e29bfe6"
      url "https://github.com/andpalmier/tfox/releases/download/v#{version}/tfox_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ce34e44bd90c8c40ef82459a47c95c41587a37f4022bfc493648fcd48fc563ab"
      url "https://github.com/andpalmier/tfox/releases/download/v#{version}/tfox_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "69bd50b1c58b3f96d46ca1cfeed5ef1aa0514fd0d807174393ffbb2bb5d7f0ee"
      url "https://github.com/andpalmier/tfox/releases/download/v#{version}/tfox_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tfox"
  desc "CLI tool to search in ThreatFox IOC database"
  homepage "https://github.com/andpalmier/tfox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfox"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfox"]
    end
  end

  # No zap stanza required
end
