# This file was generated by GoReleaser. DO NOT EDIT.
cask "urlhs" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "1ffe3eec9d25b28e5e70f1a8aeb1d4b12e032c32111f524258784455152bdcfb"
      url "https://github.com/andpalmier/urlhs/releases/download/v#{version}/urlhs_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/andpalmier/urlhs"
    end
    on_intel do
      sha256 "0e64ee1b6133232e03c8a95e052600ac5d99d638a388330d8786cec353736a04"
      url "https://github.com/andpalmier/urlhs/releases/download/v#{version}/urlhs_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/andpalmier/urlhs"
    end
  end
  on_linux do
    on_arm do
      sha256 "f2d0036c88fa56695c427eea33f78e336fe8343c4dc79fdb79e4a84cbd9fead3"
      url "https://github.com/andpalmier/urlhs/releases/download/v#{version}/urlhs_#{version}_linux_arm64.tar.gz",
        verified: "github.com/andpalmier/urlhs"
    end
    on_intel do
      sha256 "86cd26b27c29b5df494728362f79fe6bdaa41fafd615d4c62687a86d07e02dac"
      url "https://github.com/andpalmier/urlhs/releases/download/v#{version}/urlhs_#{version}_linux_amd64.tar.gz",
        verified: "github.com/andpalmier/urlhs"
    end
  end

  name "urlhs"
  desc "CLI tool to search in URLhaus database and submit URLs"
  homepage "https://github.com/andpalmier/urlhs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "urlhs"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/urlhs"]
    end
  end

  # No zap stanza required
end
