# This file was generated by GoReleaser. DO NOT EDIT.
cask "urlhs" do
  name "urlhs"
  desc "CLI tool to search in URLhaus database and submit URLs"
  homepage "https://github.com/andpalmier/urlhs"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "urlhs"

  on_macos do
    on_intel do
      url "https://github.com/andpalmier/urlhs/releases/download/v#{version}/urlhs_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/andpalmier/urlhs"
      sha256 "10832d917be9919b28da50360a772dacf360783d7e8a2df3a242b86273768ecd"
    end
    on_arm do
      url "https://github.com/andpalmier/urlhs/releases/download/v#{version}/urlhs_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/andpalmier/urlhs"
      sha256 "3d3481f8d5943bd2cf0b4c47cf6a026751f0cbfc9e1e1f54ba557f211c0d251f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andpalmier/urlhs/releases/download/v#{version}/urlhs_#{version}_linux_amd64.tar.gz",
        verified: "github.com/andpalmier/urlhs"
      sha256 "6ba0b0ebff9647e37a057deee4d338d22028329ab9ba1e3032d1dc0c2df8552a"
    end
    on_arm do
      url "https://github.com/andpalmier/urlhs/releases/download/v#{version}/urlhs_#{version}_linux_arm64.tar.gz",
        verified: "github.com/andpalmier/urlhs"
      sha256 "590db2b553bc67ccaf1f4a46c1f8edc3adbf0cc5abc5f0f80da647dbed696c08"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/urlhs"]
    end
  end

  # No zap stanza required
end
