# This file was generated by GoReleaser. DO NOT EDIT.
cask "urlhs" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "f614d34f92ac984d98c4c0b696744275023d6bd42a8bc4668c20355733d28872"
      url "https://github.com/andpalmier/urlhs/releases/download/v#{version}/urlhs_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/andpalmier/urlhs"
    end
    on_intel do
      sha256 "6b92438a5df10b680321bc425499d34583026393d81f965ea6bce54841201426"
      url "https://github.com/andpalmier/urlhs/releases/download/v#{version}/urlhs_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/andpalmier/urlhs"
    end
  end
  on_linux do
    on_arm do
      sha256 "dbfb8395573d5c4dcca0fe9b07d315fe67e4c3788e4b383b1e128d50f345de6f"
      url "https://github.com/andpalmier/urlhs/releases/download/v#{version}/urlhs_#{version}_linux_arm64.tar.gz",
        verified: "github.com/andpalmier/urlhs"
    end
    on_intel do
      sha256 "7e487e73c017d972e24e531f1c0dd516c363863cb7da31350118f20e36bdce93"
      url "https://github.com/andpalmier/urlhs/releases/download/v#{version}/urlhs_#{version}_linux_amd64.tar.gz",
        verified: "github.com/andpalmier/urlhs"
    end
  end

  name "urlhs"
  desc "CLI tool to search in URLhaus database and submit URLs"
  homepage "https://github.com/andpalmier/urlhs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "urlhs"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/urlhs"]
    end
  end

  # No zap stanza required
end
