# This file was generated by GoReleaser. DO NOT EDIT.
cask "yrfy" do
  name "yrfy"
  desc "CLI tool to interact with YARAify API"
  homepage "https://github.com/andpalmier/yrfy"
  version "0.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yrfy"

  on_macos do
    on_intel do
      url "https://github.com/andpalmier/yrfy/releases/download/v#{version}/yrfy_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/andpalmier/yrfy"
      sha256 "a594eadb71e6e2dcde2ae0daebb4de76646795700049b59f92351efc79e49b1e"
    end
    on_arm do
      url "https://github.com/andpalmier/yrfy/releases/download/v#{version}/yrfy_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/andpalmier/yrfy"
      sha256 "5367cfd9ff1aef4660c13d39e1b8205c1ffce2fbbb2d583b791d19dc016e1d2c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andpalmier/yrfy/releases/download/v#{version}/yrfy_#{version}_linux_amd64.tar.gz",
        verified: "github.com/andpalmier/yrfy"
      sha256 "ec56762d4e3ac07c30ecfdd04511d6ac5a547a7b8cc3da1c107cc8aa45545acd"
    end
    on_arm do
      url "https://github.com/andpalmier/yrfy/releases/download/v#{version}/yrfy_#{version}_linux_arm64.tar.gz",
        verified: "github.com/andpalmier/yrfy"
      sha256 "31def04fadc8c841a464fe5deee7188ec7ad25bf9ae6399b7971a471faa421c9"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yrfy"]
    end
  end

  # No zap stanza required
end
