# This file was generated by GoReleaser. DO NOT EDIT.
cask "yrfy" do
  name "yrfy"
  desc "CLI tool to interact with YARAify API"
  homepage "https://github.com/andpalmier/yrfy"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yrfy"

  on_macos do
    on_intel do
      url "https://github.com/andpalmier/yrfy/releases/download/v#{version}/yrfy_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/andpalmier/yrfy"
      sha256 "558761923038c127724b71a1ff734208ec49f5b49b86e817f1dc14920fa08f12"
    end
    on_arm do
      url "https://github.com/andpalmier/yrfy/releases/download/v#{version}/yrfy_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/andpalmier/yrfy"
      sha256 "cecfe433feacefdf51be371f42694c319f44ccea958888e33b6a86b284ccb202"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andpalmier/yrfy/releases/download/v#{version}/yrfy_#{version}_linux_amd64.tar.gz",
        verified: "github.com/andpalmier/yrfy"
      sha256 "c6ff28b71682ab4264ae422c21c918b0404ae891d37056f786bc1e9cb30cf589"
    end
    on_arm do
      url "https://github.com/andpalmier/yrfy/releases/download/v#{version}/yrfy_#{version}_linux_arm64.tar.gz",
        verified: "github.com/andpalmier/yrfy"
      sha256 "aeba917c05f41c609f9431b0d71fc60f9b3d0d6359836d4001c81a0641650bbe"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yrfy"]
    end
  end

  # No zap stanza required
end
