# This file was generated by GoReleaser. DO NOT EDIT.
cask "yrfy" do
  name "yrfy"
  desc "CLI tool to interact with YARAify API"
  homepage "https://github.com/andpalmier/yrfy"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yrfy"

  on_macos do
    on_intel do
      url "https://github.com/andpalmier/yrfy/releases/download/v#{version}/yrfy_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/andpalmier/yrfy"
      sha256 "73c386f97aa1a25154c99e3984b715fb8bc0e8242ca073a859984b19f2f5ae1e"
    end
    on_arm do
      url "https://github.com/andpalmier/yrfy/releases/download/v#{version}/yrfy_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/andpalmier/yrfy"
      sha256 "f9bfdd58d3e362f1f9cbb33126f7eeca128d8d47d7a389c9825ce3f8b78a75c0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andpalmier/yrfy/releases/download/v#{version}/yrfy_#{version}_linux_amd64.tar.gz",
        verified: "github.com/andpalmier/yrfy"
      sha256 "97c0b7f9ab18fe69ca26c554faecb402384bf8f2b878cc02d12b214d57960a80"
    end
    on_arm do
      url "https://github.com/andpalmier/yrfy/releases/download/v#{version}/yrfy_#{version}_linux_arm64.tar.gz",
        verified: "github.com/andpalmier/yrfy"
      sha256 "caeeb5c5f1433429709dd78fcb4d7f31a378a2041d39cc9f67556ae5b057be2e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yrfy"]
    end
  end

  # No zap stanza required
end
