# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apkingo < Formula
  desc "Tool to extract info from APK files"
  homepage "https://github.com/andpalmier/apkingo"
  version "2.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andpalmier/apkingo/releases/download/v2.0.1/apkingo_Darwin_x86_64.tar.gz"
      sha256 "ef1b419a60f3057742e59ce1e89c5598436fcb290400553df1bdd17eb700f0e8"

      def install
        bin.install "apkingo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andpalmier/apkingo/releases/download/v2.0.1/apkingo_Darwin_arm64.tar.gz"
      sha256 "bf5fe7c1ddb5f8505c30f0ee326577b4cc81028d57edc0c6be991937e17ad670"

      def install
        bin.install "apkingo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andpalmier/apkingo/releases/download/v2.0.1/apkingo_Linux_x86_64.tar.gz"
      sha256 "6fa9588e9408b34c5e551bbd9be11ac56032494b1ad51df834174ba29deda250"
      def install
        bin.install "apkingo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andpalmier/apkingo/releases/download/v2.0.1/apkingo_Linux_arm64.tar.gz"
      sha256 "2cb9e4610b49b4fadeb26de8bd608e22e3cfb9cc34e17f7e678554fd21f8a129"
      def install
        bin.install "apkingo"
      end
    end
  end

  test do
    system "#{bin}/apkingo --help"
  end
end
