# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mbzr < Formula
  desc "MalwareBazaar CLI Client"
  homepage "https://github.com/andpalmier/mbzr"
  version "0.0.1"
  license "AGPL-3.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andpalmier/mbzr/releases/download/v0.0.1/mbzr_Darwin_x86_64.tar.gz"
      sha256 "7d28013585931ed4826474e5e489b8d4c642ebe4d601e961a8ec5219511d4fff"

      def install
        bin.install "mbzr"

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/mbzr", "completion", "bash")
        (bash_completion/"mbzr").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/mbzr", "completion", "zsh")
        (zsh_completion/"_mbzr").write output

        # Install fish completion
        output = Utils.safe_popen_read("#{bin}/mbzr", "completion", "fish")
        (fish_completion/"mbzr.fish").write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andpalmier/mbzr/releases/download/v0.0.1/mbzr_Darwin_arm64.tar.gz"
      sha256 "4499d86194b7e57a09912c2bf1f81027865206b3ff6fe4c955672f45e0c6e45b"

      def install
        bin.install "mbzr"

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/mbzr", "completion", "bash")
        (bash_completion/"mbzr").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/mbzr", "completion", "zsh")
        (zsh_completion/"_mbzr").write output

        # Install fish completion
        output = Utils.safe_popen_read("#{bin}/mbzr", "completion", "fish")
        (fish_completion/"mbzr.fish").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andpalmier/mbzr/releases/download/v0.0.1/mbzr_Linux_x86_64.tar.gz"
      sha256 "2725d9e5862b7b1c9ed5553614c371dea1d662ecc0f29f5bcb0b4aba86d90ebf"
      def install
        bin.install "mbzr"

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/mbzr", "completion", "bash")
        (bash_completion/"mbzr").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/mbzr", "completion", "zsh")
        (zsh_completion/"_mbzr").write output

        # Install fish completion
        output = Utils.safe_popen_read("#{bin}/mbzr", "completion", "fish")
        (fish_completion/"mbzr.fish").write output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andpalmier/mbzr/releases/download/v0.0.1/mbzr_Linux_arm64.tar.gz"
      sha256 "e84aebcae947627435e81841450d5b0b5ecaf092f4fd0dc9b12c900c1326c916"
      def install
        bin.install "mbzr"

        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/mbzr", "completion", "bash")
        (bash_completion/"mbzr").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/mbzr", "completion", "zsh")
        (zsh_completion/"_mbzr").write output

        # Install fish completion
        output = Utils.safe_popen_read("#{bin}/mbzr", "completion", "fish")
        (fish_completion/"mbzr.fish").write output
      end
    end
  end
end
