# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repopsy < Formula
  desc "Forensic tool for analyzing git repository history"
  homepage "https://github.com/andpalmier/repopsy"
  version "1.0.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andpalmier/repopsy/releases/download/v1.0.0/repopsy_1.0.0_darwin_amd64.tar.gz"
      sha256 "749892368c9d8285c805b1416b2c95d138740b74c96563447b1b32cfa98bdc7b"

      def install
        bin.install "repopsy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andpalmier/repopsy/releases/download/v1.0.0/repopsy_1.0.0_darwin_arm64.tar.gz"
      sha256 "5febee70e3c17f5a2912e30410b84ae56f1b1d4142c40afb3f0d8c3dfa80d9a1"

      def install
        bin.install "repopsy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andpalmier/repopsy/releases/download/v1.0.0/repopsy_1.0.0_linux_amd64.tar.gz"
      sha256 "566a1bfcd14fd7b91f34c5c38bc808c14ee876c43efba4c1d81f11e1a0cf2771"
      def install
        bin.install "repopsy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andpalmier/repopsy/releases/download/v1.0.0/repopsy_1.0.0_linux_arm64.tar.gz"
      sha256 "1678ee967e9cf50b72b819449deec3073532c54555fc50a02e58a0f76b9b297b"
      def install
        bin.install "repopsy"
      end
    end
  end

  test do
    system "#{bin}/repopsy --version"
  end
end
