# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repopsy < Formula
  desc "Forensic tool for analyzing git repository history"
  homepage "https://github.com/andpalmier/repopsy"
  version "1.0.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andpalmier/repopsy/releases/download/v1.0.0/repopsy_1.0.0_darwin_amd64.tar.gz"
      sha256 "985b9efc03b63600f5c0d459c20fd2461e759b8b78166c3d15e416a6367e55cd"

      def install
        bin.install "repopsy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andpalmier/repopsy/releases/download/v1.0.0/repopsy_1.0.0_darwin_arm64.tar.gz"
      sha256 "aedfc4682257f268e039fe194696f993e2c3cbf150594093f24d6334525036a4"

      def install
        bin.install "repopsy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andpalmier/repopsy/releases/download/v1.0.0/repopsy_1.0.0_linux_amd64.tar.gz"
      sha256 "6fb9d0900b363973e2b67cd9e9ee948a09cb9347912d6b25f31c6dd3c6bfe811"
      def install
        bin.install "repopsy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andpalmier/repopsy/releases/download/v1.0.0/repopsy_1.0.0_linux_arm64.tar.gz"
      sha256 "4528d05951f2ca51a7342d590082ebf9d38e9ab3fd03892300923edd385fe283"
      def install
        bin.install "repopsy"
      end
    end
  end

  test do
    system "#{bin}/repopsy --version"
  end
end
